### ISSUE TITLE
Heyyy hiii , am trying to build a radio app using the assets_audio_player flutter package and am not able to play music , can u please help me ?

### ISSUE THREAD

**Issue by ampro88** [jhonbellidovargas/MusicReproductor#1]

**Comment by jhonbellidovargas** [comment]
Hello, provide me with more information about the error you have with the assets_audio_player package and the versions you are using.

**Comment by ampro88** [comment]
Am still in the beginning phase of my app bro , do u have discord or google meet ? so I can share my screen and explain ?

**Comment by jhonbellidovargas** [comment]
I recommend you clone the repository and run it. Send me screenshots of the error you have
